### ISSUE TITLE
Server Panic on invalid or already verified third party code.

### ISSUE THREAD

**Issue by flixoflax** [supertokens/supertokens-golang#139]
Hey, yesterday I started connecting my custom frontend with the backend.

I'm using the following SuperTokens packages:
- supertokens-auth-react (v0.22.0)
- supertokens-golang (v0.6.6)

For the backend I also use gofiber (v2.34.1).
When I implemented the frontend I was first implementing the `thirdPartySignInAndUp()` without the react `useEffect` hook which resulted in at least three api calls to my backend. 

It appears that sometimes the code wasn't present at all or already verified which caused the following server panic:

```
panic: interface conversion: interface {} is nil, not string

goroutine 33 [running]:
github.com/supertokens/supertokens-golang/recipe/thirdparty/providers.Facebook.func1.1({0xbb0a40?, 0xc000022780?}, 0x32?)
        C:/Users/flixoflax/go/pkg/mod/github.com/supertokens/supertokens-golang@v0.6.5/recipe/thirdparty/providers/facebook.go:82 +0x265
github.com/supertokens/supertokens-golang/recipe/thirdparty/api.MakeAPIImplementation.func2({{_, _}, _, _}, {_, _}, {_, _}, {0xc000287680, 0x2c}, ...)
        C:/Users/flixoflax/go/pkg/mod/github.com/supertokens/supertokens-golang@v0.6.5/recipe/thirdparty/api/implementation.go:134 +0x51e
github.com/supertokens/supertokens-golang/recipe/thirdpartyemailpassword/api.MakeAPIImplementation.func6({{_, _}, _, _}, {_, _}, {_, _}, {0xc000287680, 0x2c}, ...)
        C:/Users/flixoflax/go/pkg/mod/github.com/supertokens/supertokens-golang@v0.6.5/recipe/thirdpartyemailpassword/api/implementation.go:106 +0xa3
github.com/supertokens/supertokens-golang/recipe/thirdpartyemailpassword/api.GetThirdPartyIterfaceImpl.func1({{_, _}, _, _}, {_, _}, {_, _}, {0xc000287680, 0x2c}, ...)
        C:/Users/flixoflax/go/pkg/mod/github.com/supertokens/supertokens-golang@v0.6.5/recipe/thirdpartyemailpassword/api/thirdPartyAPIImplementation.go:35 +0xa4
github.com/supertokens/supertokens-golang/recipe/thirdparty/api.SignInUpAPI({_, _, _}, {{0xc0000ce480, 0xc0000ce488, 0xc0000ce470, 0xc0000ce478}, {0xc0000ce360, 0xc0000ce368, 0xc0000ce370, ...}, ...})
        C:/Users/flixoflax/go/pkg/mod/github.com/supertokens/supertokens-golang@v0.6.5/recipe/thirdparty/api/signinup.go:80 +0x383
github.com/supertokens/supertokens-golang/recipe/thirdparty.(*Recipe).handleAPIRequest(0x69732f687475612f?, {0xc13855?, 0x2f7966697265762f?}, 0x6e656e656b6f74?, {0x160ae2700e0?, 0xc000097590?}, 0xc0000fba20?, {{0xc0000a9db2?, 0xc000298640?}}, {0xc000280ac0, ...})
        C:/Users/flixoflax/go/pkg/mod/github.com/supertokens/supertokens-golang@v0.6.5/recipe/thirdparty/recipe.go:144 +0x29b
github.com/supertokens/supertokens-golang/recipe/thirdpartyemailpassword.(*Recipe).handleAPIRequest(0xc0000e8b00, {0xc13855, 0x9}, 0xc17072?, {0x160ae2700e0, 0xc000097590}, 0xbc0cc0?, {{0xc0000a9db2?, 0x0?}}, {0xc000280ac0, ...})
        C:/Users/flixoflax/go/pkg/mod/github.com/supertokens/supertokens-golang@v0.6.5/recipe/thirdpartyemailpassword/recipe.go:191 +0x1aa
github.com/supertokens/supertokens-golang/supertokens.(*superTokens).middleware.func2({0xcc7a10?, 0xc000295530}, 0xc00017eb00)
        C:/Users/flixoflax/go/pkg/mod/github.com/supertokens/supertokens-golang@v0.6.5/supertokens/supertokens.go:225 +0xb4b
net/http.HandlerFunc.ServeHTTP(0xc000308000?, {0xcc7a10?, 0xc000295530?}, 0xcb?)
        C:/Program Files/Go/src/net/http/server.go:2084 +0x2f
github.com/valyala/fasthttp/fasthttpadaptor.NewFastHTTPHandler.func1(0xc000308000)
        C:/Users/flixoflax/go/pkg/mod/github.com/valyala/fasthttp@v1.37.0/fasthttpadaptor/adaptor.go:57 +0x287
github.com/gofiber/adaptor/v2.HTTPHandler.func1(0xc0000e98c0)
        C:/Users/flixoflax/go/pkg/mod/github.com/gofiber/adaptor/v2@v2.1.24/main.go:27 +0x43
github.com/gofiber/adaptor/v2.HTTPMiddleware.func1(0xc0000e98c0)
        C:/Users/flixoflax/go/pkg/mod/github.com/gofiber/adaptor/v2@v2.1.24/main.go:48 +0xb2
github.com/gofiber/fiber/v2.(*Ctx).Next(0xc000308318?)
        C:/Users/flixoflax/go/pkg/mod/github.com/gofiber/fiber/v2@v2.34.0/ctx.go:799 +0x43
github.com/gofiber/fiber/v2/middleware/cors.New.func1(0xc0000e98c0)
        C:/Users/flixoflax/go/pkg/mod/github.com/gofiber/fiber/v2@v2.34.0/middleware/cors/cors.go:141 +0x292
github.com/gofiber/fiber/v2.(*App).next(0xc0000001e0, 0xc0000e98c0)
        C:/Users/flixoflax/go/pkg/mod/github.com/gofiber/fiber/v2@v2.34.0/router.go:132 +0x1be
github.com/gofiber/fiber/v2.(*App).handler(0xc0000001e0, 0x8bf397?)
        C:/Users/flixoflax/go/pkg/mod/github.com/gofiber/fiber/v2@v2.34.0/router.go:159 +0x45
github.com/valyala/fasthttp.(*Server).serveConn(0xc000066000, {0xcc87f8?, 0xc0000ce6f0})
        C:/Users/flixoflax/go/pkg/mod/github.com/valyala/fasthttp@v1.37.0/server.go:2338 +0x1268
github.com/valyala/fasthttp.(*workerPool).workerFunc(0xc000056280, 0xc0001dd600)
        C:/Users/flixoflax/go/pkg/mod/github.com/valyala/fasthttp@v1.37.0/workerpool.go:224 +0xa9
github.com/valyala/fasthttp.(*workerPool).getCh.func1()
        C:/Users/flixoflax/go/pkg/mod/github.com/valyala/fasthttp@v1.37.0/workerpool.go:196 +0x38
created by github.com/valyala/fasthttp.(*workerPool).getCh
        C:/Users/flixoflax/go/pkg/mod/github.com/valyala/fasthttp@v1.37.0/workerpool.go:195 +0x1b0
exit status 2
```

This first line could mean that somewhere in the supertokens-golang sdk a conversion happens unsafe.
For any questions regarding my implementation feel free to contact me :D

**Comment by rishabhpoddar** [comment]
This has been fixed in version 0.6.7
